[package]
name = "swarms-rs"
version = "0.1.4"
edition = "2024"
description = "A Rust implementation of the Swarms framework for building multi-agent systems"
authors = ["Kye Gomez <kye@kyegomez.com>"]
license = "Apache-2.0"
repository = "https://github.com/yourusername/swarms-rs"
documentation = "https://docs.rs/swarms-rs"
readme = "README.md"
keywords = ["ai", "agents", "swarms", "multi-agent", "llm"]
# categories = ["ai", "concurrency"]

[dependencies]
# Standard utilities
chrono = { version = "0.4", features = ["serde"] }
dashmap = { version = "6", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
erased-serde = "0.4"
futures = "0.3"
uuid = { version = "1.15", features = ["v4", "serde"] }

# Asynchronous programming
tokio = { version = "1" }

# Error handling and logging
thiserror = "2"
tracing = "0.1"

# Data processing
twox-hash = "2.1"
zstd = "0.13.3"
petgraph = { version = "0.7", default-features = false, features = [
    "stable_graph",
] }

# System interaction
reqwest = { version = "0.12", features = [
    "json",
    "stream",
    "multipart",
    "rustls-tls-native-roots",
], default-features = false }

# LLM provider
async-openai = { version = "0.28", features = ["byot"] }

[dev-dependencies]
anyhow = "1"
dotenv = "0.15"
tempfile = "3.19"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "tracing"] }
tokio-test = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mockall = "0.13"
criterion = "0.5"

[[bench]]
name = "graph_workflow_benchmarks"
harness = false
