[package]
name = "fetch-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
swarms-rs = { path = "../../swarms-rs" }
